import Head from "next/head";
import Banner from "../components/Banner";
import Post from "../components/Posts";
import { sanityClient } from "../utils/config";

export default function Home({ blogs }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />

      <Post blogs={blogs} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const query = `*[_type=="post"]{
    _id,
    title,
    author-> {
      name,
      image,
    },
    description,
    mainImage,
    slug
  }`;
  const blogs = await sanityClient.fetch(query);
  return {
    props: {
      blogs,
    },
  };
}
